### ISSUE TITLE
Question about use Wear and Mobile Emulator

### ISSUE THREAD

**Issue by vteferrer** [Mariuxtheone/Teleport#11]
I´m planning to use Teleport for communicate a mobile application with a wearable application. The first goal I´m trying to achieve is as simple as the first example you show in the README file of the project.  But I´m not able to get it going. I´ve been debugging along the Teleport code and it seems that the applications are not communicating with each other because they are not paired or associated to the same session. 

Reading a little on the internet I saw that apparently the wear emulator can only communicate with a physical phone and not to another emulator. 

My question is: can I do that? can I communicate the wear android emulator to the mobile android emulator running both at the same time? Must I do something special to achieve this?

Thanks in advance

**Comment by Mariuxtheone** [comment]
I don't think that's possible because you need Google Play Services in order to correctly configure the Android Wear companion app. 
I close the issue because it's not related to Teleport.
