### ISSUE TITLE
No callbacks in service

### ISSUE THREAD

**Issue by davidvavra** [Mariuxtheone/Teleport#12]
Hi,
version 1.1.2 brought a possibility to use callbacks instead of buggy AsyncTasks. But it's only possible for TeleportClient, not TeleportService. I need callbacks in Service, not Client, since I'm handling all incoming messages and data items in a service. So my original problem with Exceptions is not solved yet.

**Comment by thedamfr** [comment]
You use a TeleportClient in a classical Service.
But still, this can be patched.

**Comment by Mariuxtheone** [comment]
Will insert the same features of TeleportClient in TeleportService in an update soon. Stay tuned :-)

**Comment by Mariuxtheone** [comment]
Builders and Callbacks added to TeleportService in 0.1.3.
