### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ghost** [Mariuxtheone/Teleport#21]
I forked the repo. I then copied the code at the "Can I have an example of how easy is Teleport to use?"
The toasts are not showing up. I want to send a message to my phone from the wearable with some data. The example in the repo it  shows it can send toast messages to the wear. Can you provide an example of sending messages from the wearable to the phone?

**Comment by Mariuxtheone** [comment]
Since the example uses two activities, are you sure you are trying to send the message when both activities are in foreground on phone and Wear device? Also notice that the Tasks in the example are only a fire-and-forget message, because the tasks are not reset.

**Comment by ghost** [comment]
Examples inside the repo works
