### ISSUE TITLE
Does the usage of ASyncTask really necessary?

### ISSUE THREAD

**Issue by tasomaniac** [Mariuxtheone/Teleport#24]
I decided to use this cool library. But when I saw `ASyncTask`, I said what is going on? Why do we need our own `ASyncTask`?

Then, when I look at the internal code, I saw that `doInBackground` functions does not do anything at all. They just pass the parameter.

**Comment by thedamfr** [comment]
It's used to make sure that you are on the main thread.
But you can use Callbacks instead.

**Comment by tasomaniac** [comment]
There are other ways to ensure that it is on the main thread. Callback
function can be called on the main thread.

And lastly, in the advanced section of the wiki, it says that if you use
Callback method, you have to deal with background threading. You say the
opposite here.

**Comment by thedamfr** [comment]
I wrote the advanced section. 
And I'm not saying the opposite. 

If you don't use the doInBackground method and don't care about threading, then the Callback is enough. That's my point.
