### ISSUE TITLE
Eclipse ADT

### ISSUE THREAD

**Issue by Danyc0** [Mariuxtheone/Teleport#25]
Hi,
I'm being forced to use the Eclipse ADT for the Mobile side of my comms (but still using Android Studio for the watch side). Is there any advice for using this library with the Eclipse ADT?

Thanks,
Dan

**Comment by Mariuxtheone** [comment]
Hello @Danyc0, unfortunately I'm not supporting an ADT version of Teleport. By the way, you can still check out the library from Github and use the java classes in your project.
