### ISSUE TITLE
TeleportClient onConnected() and disconnect() show debug messages as errors

### ISSUE THREAD

**Issue by germanviscuso** [Mariuxtheone/Teleport#5]
Please replace Log.e with Log.d or Log.i in:
https://github.com/Mariuxtheone/Teleport/blob/master/teleportlib/src/main/java/com/mariux/teleport/lib/TeleportClient.java
since onConnected and disconnect are normal behaviors.

**Comment by Mariuxtheone** [comment]
Note taken, thanks for the heads up. :-)

**Comment by Mariuxtheone** [comment]
Fixed.
