### ISSUE TITLE
GmsClient reconnect problem

### ISSUE THREAD

**Issue by germanviscuso** [Mariuxtheone/Teleport#7]
I always get this error when running my Teleport based project:
E/GmsClient﹕ Calling connect() while still connected, missing disconnect()
Is this an issue related to how Teleport connects to the plus client?

**Comment by Mariuxtheone** [comment]
You should always manage to disconnect a TeleportClient when pausing, stopping and destroying an Activity. You can do it by calling the .disconnect() method.
